**<h1 style='text-align:center'>Hotel Recommendation</h1>**
**<h5 style='text-align:center'>By Group 4</h5>**

> ### **Members**  
> #### 1. LIM KIMHOUNG  
> #### 2. LUN TOLA
> #### 3. LONG CHANLEAP
> #### 4. RUN SAVIN
> #### 5. LAB THAVARITH

In [7]:
import os
import glob
import pandas as pd
os.chdir("C:/Users/Acer/Downloads/I3/Project/DS_Project/Booking.com/hotel_Info")

extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combineHotelInfo.csv", index=False, encoding='utf-8-sig')

In [8]:
df = pd.read_csv("combineHotelInfo.csv")
df

,Unnamed: 0,Name,Adress,Rating,URL,RoomType,RoomSize,Price
0,0,DEN HOTEL TOTONOU SIEM REAP,"497 Taphul Street, Krong Siem Reap, Siem Reap,...",9.0,https://www.booking.com/hotel/kh/den-totonou-s...,Economy Double Room,15 m²,"KHR 68,067"
1,1,DEN HOTEL TOTONOU SIEM REAP,"497 Taphul Street, Krong Siem Reap, Siem Reap,...",9.0,https://www.booking.com/hotel/kh/den-totonou-s...,Standard Double Room,20 m²,"KHR 76,318"
2,2,DEN HOTEL TOTONOU SIEM REAP,"497 Taphul Street, Krong Siem Reap, Siem Reap,...",9.0,https://www.booking.com/hotel/kh/den-totonou-s...,Standard Twin Room,20 m²,"KHR 78,381"
3,3,DEN HOTEL TOTONOU SIEM REAP,"497 Taphul Street, Krong Siem Reap, Siem Reap,...",9.0,https://www.booking.com/hotel/kh/den-totonou-s...,Double Room with Balcony,20 m²,"KHR 82,506"
4,4,DEN HOTEL TOTONOU SIEM REAP,"497 Taphul Street, Krong Siem Reap, Siem Reap,...",9.0,https://www.booking.com/hotel/kh/den-totonou-s...,Superior King Room,25 m²,"KHR 90,756"
...,...,...,...,...,...,...,...,...
55254,2,Jaya House River Park,"River Road, Treang Village, Slar Kram Commune,...",9.8,https://www.booking.com/hotel/kh/jaya-house-ri...,Junior Suite with Pool View - Free Airport Tra...,64 m²,"KHR 1,113,829"
55255,0,Jaya House River Park,"River Road, Treang Village, Slar Kram Commune,...",9.8,https://www.booking.com/hotel/kh/jaya-house-ri...,Deluxe Room - Free Airport Transfers + Mini-Bar,38 m²,"KHR 1,031,323"
55256,1,Jaya House River Park,"River Road, Treang Village, Slar Kram Commune,...",9.8,https://www.booking.com/hotel/kh/jaya-house-ri...,Deluxe Twin Room - Free Airport Transfers + Mi...,38 m²,"KHR 1,031,323"
55257,2,Jaya House River Park,"River Road, Treang Village, Slar Kram Commune,...",9.8,https://www.booking.com/hotel/kh/jaya-house-ri...,Junior Suite with Pool View - Free Airport Tra...,64 m²,"KHR 1,113,829"
55258,3,Jaya House River Park,"River Road, Treang Village, Slar Kram Commune,...",9.8,https://www.booking.com/hotel/kh/jaya-house-ri...,Junior Plunge Pool Suite - Free Airport Transf...,90 m²,"KHR 1,258,214"

In [9]:
os.chdir("C:/Users/Acer/Downloads/I3/Project/DS_Project/Booking.com/Facilities")

extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combineHotelFacilities.csv", index=False, encoding='utf-8-sig')

In [10]:
df1 = pd.read_csv("combineHotelFacilities.csv")
df1

     Unnamed: 0                         Name                      Facilities
0             0  DEN HOTEL TOTONOU SIEM REAP          Outdoor swimming pool
1             1  DEN HOTEL TOTONOU SIEM REAP                Airport shuttle
2             2  DEN HOTEL TOTONOU SIEM REAP              Non-smoking rooms
3             3  DEN HOTEL TOTONOU SIEM REAP                   Free parking
4             4  DEN HOTEL TOTONOU SIEM REAP                      Free WiFi
..          ...                          ...                             ...
953          15        Jaya House River Park                   Free parking
954          16        Jaya House River Park                     Restaurant
955          17        Jaya House River Park  Tea/coffee maker in all rooms
956          18        Jaya House River Park                            Bar
957          19        Jaya House River Park           Exceptional breakfast

[958 rows x 3 columns]